force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <displayFormat>Movie-{0000}</displayFormat>
        <label>Movie Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/picture_URL__c.field-meta.xml
<CustomField>
    <fullName>picture_URL__c</fullName>
    <label>picture_URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Booking</fullName>
            </value>
            <value>
                <fullName>Not</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Movie__c/fields/video_URL__c.field-meta.xml
<CustomField>
    <fullName>video_URL__c</fullName>
    <label>video_URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/ShowTime__c/ShowTime__c.object-meta.xml
<CustomObject>
    <label>ShowTime</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>ShowTime Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ShowTimes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ShowTime__c/fields/Movie__c.field-meta.xml
<CustomField>
    <fullName>Movie__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Movie</label>
    <referenceTo>Movie__c</referenceTo>
    <relationshipLabel>ShowTimes</relationshipLabel>
    <relationshipName>ShowTimes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ShowTime__c/fields/ShowDate__c.field-meta.xml
<CustomField>
    <fullName>ShowDate__c</fullName>
    <label>ShowDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/MovieController.cls
public with sharing class MovieController {
    @AuraEnabled(cacheable=true scope='global')
    public static Movie__c[] getMovies() {
        return [
            SELECT
                Id,
                Title__c,
                Description__c,
                Genre__c,
                picture_URL__c,
                video_URL__c,
                Status__c,
                Duration__c
            FROM Movie__c
            WITH SECURITY_ENFORCED
            ORDER BY Title__c
            LIMIT 50
        ];
    }

    @AuraEnabled(cacheable=true scope='global')
    public static Movie__c[] searchMovies(String searchKey) {
        // Return all bears when no search term
        searchKey = searchKey.trim();
        if (searchKey == '') {
            return getMovies();
        }
        // Prepare query paramters
        searchKey = '%' + searchKey + '%';
        // Execute search query
        return [
            SELECT
                Id,
                Title__c,
                Description__c,
                Genre__c,
                picture_URL__c,
                video_URL__c,
                Status__c,
                Duration__c
            FROM Movie__c
            WHERE Title__c LIKE :searchKey
            WITH SECURITY_ENFORCED
            ORDER BY Title__c
            LIMIT 50
        ];
    }

    // @AuraEnabled(cacheable=true scope='global')
    // public static Movie__c[] searchMoviesByDate(Date dateStr1, Date dateStr2) {
        
    //     if (dateStr1 == null && dateStr2 == null) {
    //         return getMovies();
    //     }

    //     // Prepare query parameters
    //     Date searchDate1 = dateStr1;
    //     Date searchDate2 = dateStr2;

    //     return [
    //         SELECT
    //             Id,
    //             Title__c,
    //             Description__c,
    //             Genre__c,
    //             picture_URL__c,
    //             video_URL__c,
    //             Status__c,
    //             Duration__c
    //         FROM Movie__c
    //         WHERE Id IN (
    //             SELECT Movie__c
    //             FROM ShowTime__c
    //             WHERE ShowDate__c >= :searchDate1 AND ShowDate__c <= :searchDate2)
    //         WITH SECURITY_ENFORCED
    //         ORDER BY Title__c
    //         LIMIT 50
    //     ];
    // }

//     @AuraEnabled(cacheable=true scope='global')
    // public static Movie__c[] searchMovies(String searchKey, Date startDate, Date endDate) {
    //     // Return all movies when no search term and no date range
    //     searchKey = searchKey.trim();
    //     if (searchKey == '' && startDate == null && endDate == null) {
    //         return getMovies();
    //     }
    //     // Prepare query parameters
    //     searchKey = '%' + searchKey + '%';
    //     DateTime startDateTime = startDate != null ? DateTime.newInstance(startDate.year(), startDate.month(), startDate.day(), 0, 0, 0) : null;
    //     DateTime endDateTime = endDate != null ? DateTime.newInstance(endDate.year(), endDate.month(), endDate.day(), 23, 59, 59) : null;
        
    //     // Build the dynamic query
    //     String query = 'SELECT Id, Title__c, Description__c, Genre__c, picture_URL__c, video_URL__c, Status__c, Duration__c ' +
    //                    'FROM Movie__c ' +
    //                    'WHERE 1=1 ';
                    
    //     if (searchKey != '') {
    //         query += 'AND Title__c LIKE :searchKey ';
    //     }
    //     if (startDate != null && endDate != null) {
    //         query += 'AND Id IN (SELECT Movie__c FROM ShowTime__c WHERE ShowDate__c >= :startDate AND ShowDate__c <= :endDate) ';
    //     }
        
    //     query += 'WITH SECURITY_ENFORCED ORDER BY Title__c LIMIT 50';
        
    //     // Execute search query
    //     return Database.query(query);
    // }
}