force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Membership Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <label>Rank</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Membership__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MembershipController.cls
public with sharing class MembershipController {
@AuraEnabled(cacheable=true)
    public static Membership__c getMemberships() {
        String currentUserId = UserInfo.getUserId();
        List<Membership__c> memberships = [ SELECT Id, Name, Rank__c,Address__c,Email__c 
                                            FROM Membership__c 
                                            WHERE User__c = :currentUserId
                                            LIMIT 1];
        if (memberships != NULL && !memberships.isEmpty()) {
            return memberships.get(0);
        }
        return null;
    }
}